name: dson_adapter
description: Convert JSON to Dart Class withless code generate(build_runner)
version: 1.1.0
repository: https://github.com/Flutterando/dson_adapter

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
